### ISSUE TITLE
Akord + React/Vite 504 Error

### ISSUE THREAD

**Issue by phuybregts** [Akord-com/akord-js#190]
Hi all,

Have any of you encountered the same 504 error when attemting to use Akord-JS ("^3.8.4") in a Vite ("^4.3.9") project? If yes, have you found any solution on how to solve it? It may not be a problem related to Akord-JS but rather VIte however this error renders the use of the Akord-JS package useless for those working in React/Vite.

Kind regards,

Patrick

Merely adding `import { Akord } from "@akord/akord-js"` in component causes error in console: `GET http://localhost:5174/node_modules/.vite/deps/@akord_akord-js.js?v=4d83f8e6 net::ERR_ABORTED 504 (Outdated Optimize Dep)`

**Comment by jarrvis** [comment]
Hi @phuybregts ,
thanks for reporting.
Seems like Vite is detecting incorrect path in package's `main`.
One of our internal packages (`@akord/ts-cacheable`) was published without its cjs artifact which its `main` references. This was fixed now in the linked PR.
Installing `@akord/akord-js@latest` should do the trick

**Comment by phuybregts** [comment]
@jarrvis , Hi yes that worked however it spawned another error that seems to point towards the wallet configuration. I have added another snippet of my console which describes the error: 
![AkordJSissue2](https://github.com/Akord-com/akord-js/assets/100289414/01c593b9-62e6-4fad-a8ac-82369085ace5)

Am I overlooking something here? Do I need to add and/or configure Akord wallet settings prior to importing AkordJS (or perhaps simultaneously?)

**Comment by jarrvis** [comment]
fixed by polyfilling nodeJs modules.
Vite + React starter for reference:
https://github.com/Akord-com/recipes/tree/main/react-vite-starter
