### ISSUE TITLE
Akord-JS: delete vault 404

### ISSUE THREAD

**Issue by phuybregts** [Akord-com/akord-js#202]
`const { transactionId } = await akord.vault.delete(vId);` results in 

![image](https://github.com/Akord-com/akord-js/assets/100289414/1f5e284f-f626-4a18-8e36-5261941f979b)

Data @ https://api.akord.com/vaults/b2ab90b1-62f0-4713-8a10-2c2bb1bcce82 > ` {"msg":"Missing authorization header.","success":false}`

Additional info: vault is showing up in v2.akord and vId is confirmed.

**Comment by jarrvis** [comment]
Closing this after discussing with @phuybregts - feature works correctly
