### ISSUE TITLE
Feature Request: REST API and SDK payment integration

### ISSUE THREAD

**Issue by VDD2004** [Akord-com/akord-js#298]
I'm developing an app through my company that would have end-users purchase Arweave storage through our App by utilizing the Akord API.
 
Details:
I've integrated Stripe payment into the app but am in need of a feature that allows automation of the process of purchasing Arweave storage through Akord's API or SDK.

**Comment by jarrvis** [comment]
Hi @VDD2004 ,
thanks for bringing this up.

We are considering adding a `storage` module:
`akord.storage.get()` - gives your current storage balance
`akord.storage.buy({ storageInGbs: number, simulate: boolean })` - uses your currently configured payment method and currency to pay for more permanent storage. Returns payed amount

Would that work for you?

**Comment by VDD2004** [comment]
Yes, that would work very well. We shouldn't need any complex payment system since that would be handled more on our backend. Also, in that system how could external funds get deposited automatically, if possible?

**Comment by jarrvis** [comment]
> Yes, that would work very well. We shouldn't need any complex payment system since that would be handled more on our backend. Also, in that system how could external funds get deposited automatically, if possible?

The new API is already under tests. Will release it very soon 👏 
`akord.storage.buy()` requires the user to configure the payment details before - using the frontend app. There we can validate payment details without sending those to our backend services.

So for new account, to automate the payments:
- go to frontend app -> configure your billing details
-- use SDK (akord-js) to buy storage whenever needed using `akord.storage.buy()
-- ...or use REST API to do same thing

Its still on the user when to call that method.
Is that helpful API for you usecase? Or maybe you're rather looking also for a way of detecting that your storage balance is low?

**Comment by VDD2004** [comment]
That would be perfect. Also, the storage balance detection wouldn't be something that we would need.

Thank you!

**Comment by jarrvis** [comment]
Hi @VDD2004  this feature was added on [REST API](https://api.akord.com/docs/#post-/payments) & [SDK](https://github.com/Akord-com/akord-js?tab=readme-ov-file#buy)
Please let us know if you need any changes around that (or other) feature

**Comment by VDD2004** [comment]
No problem. Once again, thank you!
