### ISSUE TITLE
akord.storage.buy() seems to not be working

### ISSUE THREAD

**Issue by VDD2004** [Akord-com/akord-js#320]
When using akord.storage.buy(1) (using an American Express credit card that has previously been used to purchase storage in Akord through the frontend,) I get back the payment object as expected 
'
{
  paymentId: 'pi_example',
  amount: 12,
  currencyCode: 'usd',
  clientSecret: 'pi_example_secret_example'
}
'
But, the card never gets charged and storage is never added to my account. I am developing an app and this feature is necessary for the project. 

Thank you for your time

**Comment by jarrvis** [comment]
Hi @VDD2004 ,
it's done like this by design. Payments by default are 2-step functions.
Please have a look at our examples in docs:
https://github.com/Akord-com/akord-js?tab=readme-ov-file#buy

here is how you can buy storage in 2 steps:
```javascript
const { paymentId, amount, currencyCode } = await akord.storage.buy(3); // initiate payment for 3 GB's: no storage increase yet, no payment yet

await akord.storage.buy({ paymentId }); // confirm the payment: storage increase after successful payment
```

you can also auto-confirm the payment in single step:
```javascript
const { paymentId, amount, currencyCode } = await akord.storage.buy(3, { currencyCode: 'EUR', confirm: true }); // auto-confirm payment for 3 GB's: storage increase after successful payment
```

**Comment by VDD2004** [comment]
Oh, I feel like I should have known that; I only looked though the api docs and not the documentation on Github. Sorry for the trouble.
