### ISSUE TITLE
API access based on public keys

### ISSUE THREAD

**Issue by rcaetano** [Akord-com/akord-js#76]
Allowing users to be authenticated on the API using their public keys.

Scenario 1:  User has an Akord wallet + account
- user logs in to cognito 
- downloads/decrypts wallet to access public key
- using private key, generate JWT token to access API

Scenario 2: User has a public/private key generated outside of Akord
- using private key, generate JWT token to access API

**Comment by jarrvis** [comment]
As a remark to this feature request: one thing to remember is not to throw private key over http while negotiating the token. To negotiate JWT using private key challenge-respons should be used.

**Comment by wkolod** [comment]
included in airdrop release: https://github.com/Akord-com/akord-js/releases/tag/v4.2.0
