### ISSUE TITLE
feat: use API key for server-to-server scenario

### ISSUE THREAD

**Issue by jarrvis** [Akord-com/akord-js#79]
For a server to server scenario, support for API key authentication could be an option. This is to avoid manual negotiation and refreshing of oauth token. 
For the tooling to generate / rotate API key:

1. add a section in the app, around Settings, could be a subsection: Developer settings -> user can generate / rotate API keys there. Maybe also see some API usage statistics
2. add API key generate / rotate in CLI
3. add API endpoint to store the key
4. add a way of initialisation of akord-js with API key - API key should only allow to access the API in user account / organisation context. API key should not be a replacement of password / backup phrase. On the server akord-js can be initialised with:
- API key - if access to API is needed (to access the API without token refresh)
- backup phrase - if de/-encryption is needed

**Comment by pascaljb** [comment]
@rcaetano mentioned analytics for org use case - I think this is great idea. I'm thinking "Settings" could become "Account" and hold "Developer settings" as you suggest when applicable, but also include an "Analytics" tab, which we can develop for paying clients
